-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgY9r/Jnh6WumhxGgJ
96Nkrct9t0HXk4p/jyeqO/1ACSWgCgYIKoZIzj0DAQehRANCAASplQtrR2rqd6HN
9xJQfqmi9p+fCT3tzpK6lTN8zCnzyzxKBGeiHgiEXcD1xhc+xKNf9lmkoR3yvaql
CvqWHCOR
-----END PRIVATE KEY-----