<?php namespace backend\models;

use common\components\caching\Cache;
use Yii;

class AdBanner extends \common\models\AdBanner
{
    private const ATTRIBUTES = [
        'enabled',
        'type',
        'platform',
        'provider',
        'position',
        'repeat_factor',
        'limit',
        'categories',
        'country',
    ];
    private const DEFAULT_ROWS_FOR_COUNTRY = [
        [
            'enabled' => 1,
            'type' => 'category',
            'platform' => 'android',
            'provider' => 'googlead',
            'position' => 2,
            'repeat_factor' => null,
            'limit' => null,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'feed',
            'platform' => 'android',
            'provider' => 'googlead',
            'position' => 2,
            'repeat_factor' => null,
            'limit' => null,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'category',
            'platform' => 'android',
            'provider' => 'googlead',
            'position' => 15,
            'repeat_factor' => 15,
            'limit' => 5,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'feed',
            'platform' => 'android',
            'provider' => 'googlead',
            'position' => 15,
            'repeat_factor' => 15,
            'limit' => 5,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'category',
            'platform' => 'ios',
            'provider' => 'googlead',
            'position' => 2,
            'repeat_factor' => null,
            'limit' => null,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'feed',
            'platform' => 'ios',
            'provider' => 'googlead',
            'position' => 2,
            'repeat_factor' => null,
            'limit' => null,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'category',
            'platform' => 'ios',
            'provider' => 'googlead',
            'position' => 15,
            'repeat_factor' => 15,
            'limit' => 5,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'feed',
            'platform' => 'ios',
            'provider' => 'googlead',
            'position' => 15,
            'repeat_factor' => 15,
            'limit' => 5,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'atricle',
            'platform' => 'android',
            'provider' => 'googlead',
            'position' => null,
            'repeat_factor' => null,
            'limit' => null,
            'categories' => '[]',
            'country' => ''
        ],
        [
            'enabled' => 1,
            'type' => 'atricle',
            'platform' => 'ios',
            'provider' => 'googlead',
            'position' => null,
            'repeat_factor' => null,
            'limit' => null,
            'categories' => '[]',
            'country' => ''
        ],
    ];

    public function afterSave($insert, $changedAttributes)
    {
        Cache::clearByTag(Cache::TAG_AD_BANNERS_LIST);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function createDefaultsForCountry($country_code)
    {
        $defaults = self::DEFAULT_ROWS_FOR_COUNTRY;
        array_walk($defaults, function (&$item) use ($country_code) {
            $item['country'] = $country_code;
        });
        Yii::$app->db->createCommand()->batchInsert(self::tableName(), self::ATTRIBUTES, $defaults)->execute();
    }

}